version: '3.8'
services:

  app-backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: java -jar ./app.jar
    restart: always
    image: 'roman2301/hello_spring'
    ports:
      - 9090:9090


